In [17]:
from bokeh.io import output_notebook, output_file
from bokeh.plotting import figure, show, ColumnDataSource, curdoc
import pandas as pd
from bokeh.models import CategoricalColorMapper, HoverTool
from bokeh.embed import components
from bokeh.layouts import column, row, widgetbox
import numpy as np
import json

In [18]:
#data I need high, low, open, close, volume, percent change, symbol for 9/25/2020
#4 categories
#Equities: ES, NQ, RTY, YM
#Energys: CL, NG, HO
#Metals: Gold, Silver, Copper, Platinum
#Currencies: DXY, Euro, Australian Dollar, Japanese Yen, Swiss Franc, Canadian Dollar, British Pound

In [19]:
# Importing Equities Data
es = pd.read_csv('./data/ES=F.csv')
es['symbol'] = 'ES'
nq = pd.read_csv('./data/NQ=F.csv')
nq['symbol'] = 'NQ'
rty = pd.read_csv('./data/RTY=F.csv')
rty['symbol'] = 'RTY'
ym = pd.read_csv('./data/YM=F.csv')
ym['symbol'] = 'YM'

In [20]:
# Joining Equities Tables, dropping 9/24 rows, adding percent change column, add Category column
equities = es.append([nq, rty, ym])
equities['Category'] = 'Equity'
equities = equities[equities.Date=='2020-09-25']
equities['percent_change'] = ((equities['Close']-equities['Open'])/equities['Open'])*100
equities

,Date,Open,High,Low,Close,Adj Close,Volume,symbol,Category,percent_change
1,2020-09-25,3243.500000,3296.250000,3206.500000,3287.250000,3287.250000,2277010,ES,Equity,1.348852
1,2020-09-25,10914.200195,11166.200195,10813.799805,11136.500000,11136.500000,791934,NQ,Equity,2.036794
1,2020-09-25,1450.300049,1474.199951,1428.900024,1467.199951,1467.199951,239509,RTY,Equity,1.165269
1,2020-09-25,26772.000000,27123.000000,26424.000000,27043.000000,27043.000000,254511,YM,Equity,1.012252

In [21]:
# Importing Energies Data
cl = pd.read_csv('./data/CL=F.csv')
cl['symbol'] = 'CL'
ng = pd.read_csv('./data/NG=F.csv')
ng['symbol'] = 'NG'
ho = pd.read_csv('./data/HO=F.csv')
ho['symbol'] = 'HO'

In [22]:
# Joining Energies Tables, dropping 9/24 rows, adding percent change column, add Category column
energies = cl.append([ng, ho])
energies['Category'] = 'Energy'
energies = energies[energies.Date=='2020-09-25']
energies['percent_change'] = ((energies['Close']-energies['Open'])/energies['Open'])*100
energies

,Date,Open,High,Low,Close,Adj Close,Volume,symbol,Category,percent_change
1,2020-09-25,40.150002,40.639999,39.709999,40.2500,40.2500,269992,CL,Energy,0.249061
1,2020-09-25,2.178000,2.260000,2.101000,2.1390,2.1390,60475,NG,Energy,-1.790634
1,2020-09-25,1.112000,1.128100,1.109500,1.1262,1.1262,19622,HO,Energy,1.276978

In [23]:
# Importing Metals Data
gc = pd.read_csv('./data/GC=F.csv')
gc['symbol'] = 'GC'
si = pd.read_csv('./data/SI=F.csv')
si['symbol'] = 'SI'
pl = pd.read_csv('./data/PL=F.csv')
pl['symbol'] = 'PL'
hg = pd.read_csv('./data/HG=F.csv')
hg['symbol'] = 'Hg'

In [24]:
# Joining metals Tables, dropping 9/24 rows, adding percent change column, add Category column
metals = gc.append([si, pl, hg])
metals['Category'] = 'Metal'
metals = metals[metals.Date=='2020-09-25']
metals['percent_change'] = ((metals['Close']-metals['Open'])/metals['Open'])*100
metals

,Date,Open,High,Low,Close,Adj Close,Volume,symbol,Category,percent_change
1,2020-09-25,1856.300049,1857.699951,1856.300049,1857.699951,1857.699951,365,GC,Metal,0.075414
1,2020-09-25,22.750000,23.017000,22.730000,23.017000,23.017000,43,SI,Metal,1.173626
1,2020-09-25,841.099976,841.099976,841.099976,841.099976,841.099976,4,PL,Metal,0.000000
1,2020-09-25,2.983000,2.991000,2.952500,2.973000,2.973000,351,Hg,Metal,-0.335233

In [25]:
# Importing Currencies Data
a = pd.read_csv('./data/6A=F.csv')
a['symbol'] = '6A'
b = pd.read_csv('./data/6B=F.csv')
b['symbol'] = '6B'
c = pd.read_csv('./data/6C=F.csv')
c['symbol'] = '6C'
e = pd.read_csv('./data/6E=F.csv')
e['symbol'] = '6E'
j = pd.read_csv('./data/6J=F.csv')
j['symbol'] = '6J'
s = pd.read_csv('./data/6S=F.csv')
s['symbol'] = '6S'

In [26]:
# Joining Currencies Tables, dropping 9/24 rows, adding percent change column, add Category column
currencies = a.append([b, c, e, j, s])
currencies['Category'] = 'Currency'
currencies = currencies[currencies.Date=='2020-09-25']
currencies['percent_change'] = ((currencies['Close']-currencies['Open'])/currencies['Open'])*100
currencies

,Date,Open,High,Low,Close,Adj Close,Volume,symbol,Category,percent_change
1,2020-09-25,0.705400,0.7088,0.700700,0.702500,0.702500,469,6A,Currency,-0.411114
1,2020-09-25,1.275800,1.2803,1.269000,1.273200,1.273200,609,6B,Currency,-0.203794
1,2020-09-25,0.749100,0.7495,0.745600,0.746550,0.746550,67,6C,Currency,-0.340408
1,2020-09-25,1.167800,1.1690,1.161950,1.162750,1.162750,448,6E,Currency,-0.432437
1,2020-09-25,0.009497,0.0095,0.009468,0.009472,0.009472,80,6J,Currency,-0.263241
1,2020-09-25,1.081600,1.0833,1.078100,1.079000,1.079000,27063,6S,Currency,-0.240385

In [27]:
#adding all the tables together
futures = equities.append([energies, metals, currencies]).reset_index().drop('index', axis=1).reset_index()
futures['size'] = pd.cut(futures.Volume, bins = [0, 500, 5000, 50000, 500000, 5000000], labels = [15,30,45,60,75])
futures

,index,Date,Open,High,Low,Close,Adj Close,Volume,symbol,Category,percent_change,size
0,0,2020-09-25,3243.500000,3296.250000,3206.500000,3287.250000,3287.250000,2277010,ES,Equity,1.348852,75
1,1,2020-09-25,10914.200195,11166.200195,10813.799805,11136.500000,11136.500000,791934,NQ,Equity,2.036794,75
2,2,2020-09-25,1450.300049,1474.199951,1428.900024,1467.199951,1467.199951,239509,RTY,Equity,1.165269,60
3,3,2020-09-25,26772.000000,27123.000000,26424.000000,27043.000000,27043.000000,254511,YM,Equity,1.012252,60
4,4,2020-09-25,40.150002,40.639999,39.709999,40.250000,40.250000,269992,CL,Energy,0.249061,60
5,5,2020-09-25,2.178000,2.260000,2.101000,2.139000,2.139000,60475,NG,Energy,-1.790634,60
6,6,2020-09-25,1.112000,1.128100,1.109500,1.126200,1.126200,19622,HO,Energy,1.276978,45
7,7,2020-09-25,1856.300049,1857.699951,1856.300049,1857.699951,1857.699951,365,GC,Metal,0.075414,15
8,8,2020-09-25,22.750000,23.017000,22.730000,23.017000,23.017000,43,SI,Metal,1.173626,15
9,9,2020-09-25,841.099976,841.099976,841.099976,841.099976,841.099976,4,PL,Metal,0.000000,15
10,10,2020-09-25,2.983000,2.991000,2.952500,2.973000,2.973000,351,Hg,Metal,-0.335233,15
11,11,2020-09-25,0.705400,0.708800,0.700700,0.702500,0.702500,469,6A,Currency,-0.411114,15
12,12,2020-09-25,1.275800,1.280300,1.269000,1.273200,1.273200,609,6B,Currency,-0.203794,30
13,13,2020-09-25,0.749100,0.749500,0.745600,0.746550,0.746550,67,6C,Currency,-0.340408,15
14,14,2020-09-25,1.167800,1.169000,1.161950,1.162750,1.162750,448,6E,Currency,-0.432437,15
15,15,2020-09-25,0.009497,0.009500,0.009468,0.009472,0.009472,80,6J,Currency,-0.263241,15
16,16,2020-09-25,1.081600,1.083300,1.078100,1.079000,1.079000,27063,6S,Currency,-0.240385,45

In [28]:
# Convert df to a ColumnDataSource: source
source = ColumnDataSource(futures)

# Make a CategoricalColorMapper object: color_mapper
color_mapper = CategoricalColorMapper(factors=['Equity', 'Energy', 'Metal', 'Currency'],
                                      palette=['red', 'purple', 'blue', 'green'])

p = figure(y_range=(-3,4), x_axis_label = "Futures Products", y_axis_label = "Percent Change", title = "Percent Changes in Futures Market for 9/25/2020")

# Add a circle glyph to the figure p
p.circle('index', 'percent_change', source=source,
         color=dict(field='Category', transform=color_mapper),
         legend_group='Category', size='size', alpha=.5,
         hover_fill_color='pink', hover_alpha=.5,
         hover_line_color='white')

p.background_fill_color = ("white")

tt = tooltips = [("Symbol", "@symbol"),
                       ("Category", "@Category"),
                       ("Percent Change", "@percent_change{0.00}"),
                       ("Open", "@Open{0.00}"),
                       ("Close", "@Close{0.00}"),
                       ("High", "@High{0.00}"),
                       ("Low", "@Low{0.00}"),
                       ("Volume", "@Volume{0.00}")]
hover = HoverTool(tooltips=tt)
p.add_tools(hover)

In [29]:
# output_notebook()

In [30]:
# show(p)

In [31]:
curdoc().add_root(column(p))

In [16]:
# !jupyter nbconvert --to script myapp.ipynb
# !bokeh serve --show myapp.py --port 8000 --allow-websocket-origin=*